version: '3.7'
services:
  db:
    build:
      context: ./docker/db
      dockerfile: Dockerfile
      # args:
      #   POSTGRES_VERSION: ${POSTGRES_VERSION}
      #   POSTGIS_VERSION: ${POSTGIS_VERSION}
      #   TIMEZONE: ${TIMEZONE}
    image: registry.ds:5000/postgis
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=user
    restart: on-failure
    healthcheck:
      test: "exit 0"

  geoserver:
    image: registry.local:5000/geoserver:2.20.0
    build: 
      context: ./docker/geoserver
      dockerfile: Dockerfile
    volumes:
      - geoserver-data:/opt/geoserver/data_dir
    ports:
      - 8600:8080
    restart: on-failure
    environment:
      - GEOSERVER_DATA_DIR=/opt/geoserver/data_dir
      - GEOWEBCACHE_CACHE_DIR=/opt/geoserver/data_dir/gwc
      - GEOSERVER_ADMIN_PASSWORD=pass
      - GEOSERVER_ADMIN_USER=user
      - INITIAL_MEMORY=2G
      - MAXIMUM_MEMORY=4G
    depends_on:
      - db
    healthcheck:
      test: curl --fail -s http://localhost:8080/ || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - 5452:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=pass
    volumes:
      - pgadmin-servers:/pgadmin4/servers.json
    logging:
      driver: none
    depends_on:
      - db

volumes:
  db:
  geoserver-data:
  pgadmin-servers:
